<!--
 * This file is part of prose-app-web
 *
 * Copyright 2023, Prose Foundation
 -->

<!-- **********************************************************************
     TEMPLATE
     ********************************************************************** -->

<template lang="pug">
.p-edit-profile-authentication
  edit-profile-form-fieldset(
    :fieldsets="fieldsets"
  )
</template>

<!-- **********************************************************************
     SCRIPT
     ********************************************************************** -->

<script lang="ts">
// PROJECT: COMPONENTS
import {
  default as EditProfileFormFieldset,
  Fieldset as FormFieldset,
  FieldsetFieldType as FormFieldsetFieldType,
  FieldsetFieldDataButton as FormFieldsetFieldDataButton
} from "@/components/popups/sidebar/EditProfileFormFieldset.vue";

export default {
  name: "EditProfileAuthentication",

  components: { EditProfileFormFieldset },

  data() {
    return {
      // --> DATA <--

      fieldsets: [
        {
          id: "password",
          title: "Account password",

          fields: [
            {
              id: "password",
              type: FormFieldsetFieldType.Button,
              label: "Password:",

              data: {
                text: "Change password…"
              } as FormFieldsetFieldDataButton
            }

            // TODO: recovery email small button
          ],

          notes: [
            "Your password is what keeps your account secure. If you forget it, you can still recover it from your recovery email. Make sure to keep it up-to-date."
          ]
        },

        {
          id: "mfa",
          title: "Multi-factor authentication",

          fields: [
            {
              id: "token",
              type: FormFieldsetFieldType.Button,
              label: "Token:",

              data: {
                text: "Disable MFA…"
              } as FormFieldsetFieldDataButton
            }

            // TODO: status + recovery small buttons
          ],

          notes: [
            "Multi-factor authentication adds an extra layer of security to your account, by asking for a temporary code generated by an app, upon login.",
            "In the event that you are unable to generate MFA tokens, you can still use your recovery phone number to login to your account."
          ]
        }
      ] as FormFieldset
    };
  }
};
</script>
