<!--
 * This file is part of prose-app-web
 *
 * Copyright 2023, Prose Foundation
 -->

<!-- **********************************************************************
     TEMPLATE
     ********************************************************************** -->

<template lang="pug">
form-settings-editor(
  :fieldsets="fieldsets"
  class="p-edit-profile-authentication"
)
</template>

<!-- **********************************************************************
     SCRIPT
     ********************************************************************** -->

<script lang="ts">
// NPM
import { PropType } from "vue";
import { JID } from "@prose-im/prose-sdk-js";

// PROJECT: COMPONENTS
import {
  default as FormSettingsEditor,
  Fieldset as FormFieldset,
  FieldsetFieldType as FormFieldsetFieldType,
  FieldsetFieldDataButton as FormFieldsetFieldDataButton,
  FieldsetControlActionType as FormFieldsetControlActionType,
  FieldsetControlActionDataButton as FormFieldsetControlActionDataButton,
  FieldsetControlIconType as FormFieldsetControlIconType
} from "@/components/form/FormSettingsEditor.vue";

export default {
  name: "EditProfileAuthentication",

  components: { FormSettingsEditor },

  props: {
    jid: {
      type: Object as PropType<JID>,
      required: true
    }
  },

  data() {
    return {
      // --> DATA <--

      fieldsets: [
        {
          id: "password",
          title: "Account password",

          fields: [
            {
              id: "password",
              type: FormFieldsetFieldType.Button,
              label: "Password:",

              data: {
                text: "Change password…",
                disabled: true
              } as FormFieldsetFieldDataButton
            }
          ],

          controls: [
            {
              id: "recovery-email",
              label: "Recovery email:",
              value: "(none)", // TODO: fetch this from somewhere

              actions: [
                {
                  type: FormFieldsetControlActionType.Button,

                  data: {
                    text: "Edit",
                    disabled: true
                  } as FormFieldsetControlActionDataButton
                }
              ]
            }
          ],

          notes: [
            "Your password is what keeps your account secure. If you forget it, you can still recover it from your recovery email. Make sure to keep it up-to-date."
          ],

          options: {
            aside: true
          }
        },

        {
          id: "mfa",
          title: "Multi-factor authentication",

          fields: [
            {
              id: "token",
              type: FormFieldsetFieldType.Button,
              label: "Token:",

              data: {
                text: "Configure MFA…",
                disabled: true
              } as FormFieldsetFieldDataButton
            }
          ],

          controls: [
            {
              id: "status",
              label: "Status:",
              value: "Disabled",
              icon: FormFieldsetControlIconType.StatusDisabled
            },

            {
              id: "recovery-phone",
              label: "Recovery phone:",
              value: "(none)", // TODO: fetch this from somewhere

              actions: [
                {
                  type: FormFieldsetControlActionType.Button,

                  data: {
                    text: "Edit",
                    disabled: true
                  } as FormFieldsetControlActionDataButton
                }
              ]
            }
          ],

          notes: [
            "Multi-factor authentication adds an extra layer of security to your account, by asking for a temporary code generated by an app, upon login.",
            "In the event that you are unable to generate MFA tokens, you can still use your recovery phone number to login to your account."
          ],

          options: {
            aside: true
          }
        }
      ] as Array<FormFieldset>
    };
  }
};
</script>
