/*
 * This file is part of prose-app-web
 *
 * Copyright 2023, Prose Foundation
 */

/**************************************************************************
 * TYPES
 * ************************************************************************* */

export type MessageID = string;
export type MessageReaction = string;

/**************************************************************************
 * ENUMERATIONS
 * ************************************************************************* */

export enum MessageType {
  // The message is sent in the context of a one-to-one chat conversation.
  Chat = "chat",
  // An error has occurred related to a previous message sent by the sender.
  Error = "error",
  // The message is sent in the context of a multi-user chat environment.
  Groupchat = "groupchat",
  // The message is probably generated by an automated service that delivers \
  //   or broadcasts content.
  Headline = "headline",
  // The message is a single message that is sent outside the context of a \
  //   one-to-one conversation or groupchat, and to which it is expected that \
  //   the recipient will reply.
  Normal = "normal"
}

export enum MessageChatState {
  // User is actively participating in the chat session.
  Active = "active",
  // User is composing a message.
  Composing = "composing",
  // User has effectively ended their participation in the chat session.
  Gone = "gone",
  // User has not been actively participating in the chat session.
  Inactive = "inactive",
  // User had been composing but now has stopped.
  Paused = "paused"
}
